tgjones/gemini

src/Gemini/Framework/Menus/ExcludeMenuDefinition.cs
src/Gemini/Framework/Menus/ExcludeMenuItemDefinition.cs
src/Gemini/Framework/Menus/ExcludeMenuItemGroupDefinition.cs
src/Gemini/Gemini.csproj
src/Gemini/Modules/MainMenu/MenuBuilder.cs

Added ExcludeMenu<xx> classes to Gemini.Framework.Menus and made edits to the Gemini.Modules.MainMenu MenuBuilder class. 
This means exported ExcludeMenu<xx> classes will remove those menu options from the default definitions file in the MainMenu module.
Example usage with the Gemini Demo project is as follows:
```c#
public static class ExcludeMenuDefinitions
{
[Export]
public static ExcludeMenuItemDefinition ExcludeOpenMenuItem = new ExcludeMenuItemDefinition(Gemini.Modules.Shell.MenuDefinitions.FileOpenMenuItem);
[Export]
public static ExcludeMenuItemGroupDefinition ExcludeWindowMenuItemGroup = new ExcludeMenuItemGroupDefinition(Gemini.Modules.MainMenu.MenuDefinitions.ViewToolsMenuGroup);
[Export]
public static ExcludeMenuDefinition ExcludeWindowMenuDefinition = new …
```

Addresses issue #129 , Default Menu Customization

---

src/Gemini.Demo/Gemini.Demo.csproj
src/Gemini.Demo/Modules/Home/ViewModels/HelixViewModel.cs
src/Gemini.Demo/packages.config
src/Gemini.Modules.CodeCompiler/CodeCompiler.cs
src/Gemini.Modules.CodeCompiler/Gemini.Modules.CodeCompiler.csproj
src/Gemini.Modules.CodeCompiler/ICodeCompiler.cs
src/Gemini.Modules.CodeCompiler/packages.config

Update Gemini.Demo and Gemini.Modules.CodeCompiler to reference Microsoft.CodeAnalysis.CSharp -Version 1.0.0.
Made all the necessary API call changes to CodeCompiler.cs and HelixViewModel.cs 
The CodeCompiler module can now be used to compile C#6 code

Update projects that reference the deprecated Roslyn.Compilers package

---

src/Gemini/Modules/Shell/Services/ILayoutItemStatePersister.cs
src/Gemini/Modules/Shell/Services/LayoutItemStatePersister.cs
src/Gemini/Modules/Shell/ViewModels/ShellViewModel.cs

If loading the persisted layout state fails, you get an empty shell. This makes the function return a status instead and if it failed the shell will create the default documents and tools.

Shell: Create default documents and tools if persisted layout state could not be loaded

---

src/Gemini.Modules.Inspector/Inspectors/CollapsibleGroupView.xaml

This adds a margin to collapsible groups to make nested groups look less flat.
It also adds a border on the left side to have a clear differentiation between nesting levels.

Inspector: Make nested collapsible groups more pretty

---

src/Gemini/AppBootstrapper.cs

Sometimes you need to run code before the initialization of the bootstrapper.
One use case for example is to install an assembly resolver to load assemblies from non default locations.
This patch adds a virtual PreInitialize function to the bootstrapper that can be overridden in subclasses to do this.

Bootstrapper: Add possibility to run code before Initialize

---

src/Gemini.Modules.Inspector/Controls/ScreenColorPicker.cs

Do not raise the PickingStarted event or start the timer if they fail.

Inspector: Check return values for Focus and CaptureMouse

---

src/Gemini/Framework/Themes/BlueTheme.cs
src/Gemini/Framework/Themes/DarkTheme.cs
src/Gemini/Framework/Themes/IThemeManager.cs
src/Gemini/Framework/Themes/LightTheme.cs
src/Gemini/Framework/Themes/ThemeManager.cs

This makes it possible to clear the list of themes on startup before the
shell is loaded and add custom themes derived from the Gemini base themes.
Example code:
```c#
[Export(typeof(ITheme))]
public class LightTheme : Gemini.Framework.Themes.LightTheme
{
public override IEnumerable<Uri> ApplicationResources
{
get {
foreach (var res in base.ApplicationResources)
yield return res;
yield return new Uri("pack://application:,,,/InteractiveAsia;component/Themes/LightTheme.xaml");
}
}
}
/* Remove default themes, add our derived themes */
_themeManager.Themes.Clear();
_themeManager.Themes.Add(new MyThemes.LightTheme());
_themeManager.Themes.Add(new MyThemes.BlueTheme());
_themeManager.Themes.Add(new MyThemes.DarkTheme());
```

ThemeManager: Make Theme list modifyable and theme functions virtual

---

src/Gemini/Modules/Shell/ViewModels/ShellViewModel.cs

There are problems with writing code that opens and closes windows based
on the active document if the ActiveDocumentChanging event occurs when the
same document is activated again. In my case I opened a new tool window
which would disappear right after ShowTool because it would raise
ActiveDocumentChanging with the same document again.

Shell: Do not raise ActiveDocumentChanging if same document gets activated again

---

src/Gemini/Framework/Behaviors/BindableTreeViewSelectedItemBehavior.cs

Fix BindableTreeViewSelectedItemBehavior to check for tree being null.

SettingsView: Fix design time exception in BindableTreeViewSelectedItemBehavior

---

src/Gemini.Modules.Inspector/Gemini.Modules.Inspector.csproj
src/Gemini.Modules.Inspector/Inspectors/ChangeObjectValueAction.cs
src/Gemini.Modules.Inspector/Inspectors/EditorBase.cs
src/Gemini.Modules.Inspector/Inspectors/RangeEditorView.xaml
src/Gemini.Modules.Inspector/Inspectors/RangeEditorViewModel.cs
src/Gemini.Modules.Inspector/Inspectors/SelectiveUndoEditorBase.cs
src/Gemini/Framework/Controls/SliderEx.cs
src/Gemini/Gemini.csproj

This makes the RangeEditor use the SelectiveUndoEditorBase to disable the
undo functionality while the user is dragging the slider, preventing
excessive ammounts of undo entries being created.

Inspector: Make RangeEditor not update the undo manager when dragging

---

src/Gemini/Gemini.csproj
src/Gemini/Themes/VS2013/BlueTheme.xaml
src/Gemini/Themes/VS2013/Controls/Merged.xaml
src/Gemini/Themes/VS2013/DarkTheme.xaml
src/Gemini/Themes/VS2013/LightTheme.xaml

Will be useful later when adding more control styles (soon)
It is also useful when you want to merge all the Gemini control styles
into an external theme.

Themes: Add merged dictionary for all controls

---

src/Gemini.Modules.Inspector/Inspectors/EditorBase.cs
src/Gemini.Modules.Inspector/Inspectors/SelectiveUndoEditorBase.cs

The EditorBase is extended by a IValueConverter property called Converter
that gets used to convert the value if its type does not match the value
type of the bound property descriptor.
This needs #188 merged first.

Inspector: Add support for value converters to editors

---

src/Gemini.Modules.Inspector/Inspectors/EditorBase.cs
src/Gemini.Modules.Inspector/Inspectors/SelectiveUndoEditorBase.cs

This means that it can be removed from SelectiveUndoEditorBase and that
editors that do not need undo can just disable it in their constructor.
This closes PR #178

Inspector: Add undo toggle to EditorBase

---

src/Gemini.Modules.Inspector/Inspectors/EditorBase.cs
src/Gemini.Modules.Inspector/Inspectors/SelectiveUndoEditorBase.cs
src/Gemini.Modules.Inspector/Resources/Resources.xaml

Adds an IsDirty property to EditorBase that can determine if the value is
dirty if the property descriptor has a DefaultValueAttribute, if it does
not it will always return true. The reset buttons IsEnabled property is
bound to this new property
Inspector: Only notify of editor property change once
The EditorBase class notified multiple times of property changes if the
bound property descriptor sent change notifications. This patch disables
notification when setting the value.
This needs #190 merged first.

Inspector: Disable reset button when value is not dirty

---

src/Gemini.Modules.Inspector/Controls/ScreenColorPicker.cs
src/Gemini.Modules.Inspector/Gemini.Modules.Inspector.csproj
src/Gemini.Modules.Inspector/Util/ScreenShotUtility.cs
src/Gemini.Modules.Inspector/Win32/NativeMethods.cs

This would cause the mouse coordinates to get negative, thereby crashing
on trying to read the pixel value from the bitmap.

Color picker: Fix for dual monitor primary screen to the right of secondary

---

src/Gemini/Themes/VS2013/Controls/Menu.xaml

Based on change suggestion in #184

Theme: Add margin to command shortcut text to prevent overlap

---

src/Gemini.Modules.Inspector/Inspectors/EditorBase.cs
src/Gemini.Modules.Inspector/Inspectors/SelectiveUndoEditorBase.cs

The selective undo editor would create an undo entry that would set the
wrong type for the bound property descriptor.

Inspector: Fix selective undo editor with type converters

---

src/Gemini.Modules.Inspector/Inspectors/ChangeObjectValueAction.cs
src/Gemini.Modules.Inspector/Inspectors/EditorBase.cs
src/Gemini.Modules.Inspector/Inspectors/SelectiveUndoEditorBase.cs

This can be used to format history items more nicely.

Inspector: Add string converter for history items

---

src/Gemini.Modules.Inspector/Inspectors/ColorEditorView.xaml
src/Gemini.Modules.Inspector/Inspectors/ColorEditorViewModel.cs

This prevents excessive undo redo entries while the user is editing the
color. The undo redo stack is updated as soon as the user closes the color
picker.

Color Picker: Disable undo redo while dialog is open

---

src/Gemini.Modules.Inspector/Gemini.Modules.Inspector.csproj
src/Gemini.Modules.Inspector/Inspectors/EditorBase.cs
src/Gemini.Modules.Inspector/Inspectors/ResetObjectValueAction.cs
src/Gemini.Modules.Inspector/Properties/Resources.Designer.cs
src/Gemini.Modules.Inspector/Properties/Resources.de.resx
src/Gemini.Modules.Inspector/Properties/Resources.resx

This creates a new ResetObjectValueAction that gets pushed to the undo
redo stack when the reset button of a value in the inspector gets pressed.

Inspector: Add reset object action to undo redo manager

---

src/Gemini/Modules/UndoRedo/IUndoRedoManager.cs
src/Gemini/Modules/UndoRedo/Services/UndoRedoManager.cs

This patch adds the UndoCountLimit property to the UndoRedoManager which
is used to limit the maximum length of the stack. By default it is set to
-1 which means that no limit is enforced. Any value below 0 is used to
disable the limit. If the value is above zero, the undo stack is always
limited to this length but the redo stack is not limited by this as it
should not get longer than the undo stack anyway as long as the limit is
not changed.

Undo Redo: Add optional limit for number of undo entries

---

src/Gemini/Modules/Shell/ViewModels/ShellViewModel.cs

The shell calls ActivateItem inside the ActiveLayoutItem setter which
causes ActiveDocumentChanged to be raised twice because ActivateItem calls
base.ActivateItem(item) which sets ActiveLayoutItem which calls
ActivateItem where the ReferenceEquals check fails to detect the duplicate
activation because ActiveItem is not updated yet.
This patch adds a guard in ActivateItem that prevents recursive calls.

Shell: Fix duplicate ActiveDocumentChanged

---

src/Gemini/Modules/Shell/Services/LayoutItemStatePersister.cs

If a stream is wrapped in a **BinaryWriter** or **BinaryReader** and '_leaveOpen_' is false (as it is by default) they will take care of closing/disposing the underlying stream. Those finally blocks are futile.
Also if the constructor of **FileStream** throws an exception, the variable 'stream' will remain null, so again: the finally blocks are futile...
I added a small bugfix too in _GetTypeFromContractNameAsILayoutItem()_. I am pretty sure **Type**._IsInstanceOf()_ does not take another Type as an argument. I think you meant something like: 'does this type implement _ILayoutItem_?'

LayoutItemStatePersister Stream Dispose clean-up

---

src/Gemini.Demo/Modules/Shell/Views/DemoApplicationSettingsView.xaml
src/Gemini.Demo/Modules/TextEditor/Views/EditorView.xaml
src/Gemini.Modules.Inspector/Resources/Resources.xaml
src/Gemini.Modules.Inspector/Themes/Generic.xaml
src/Gemini.Modules.Inspector/Views/InspectorView.xaml
src/Gemini/Gemini.csproj
src/Gemini/Modules/MainMenu/Views/MainMenuSettingsView.xaml
src/Gemini/Modules/Settings/Views/SettingsView.xaml
src/Gemini/Modules/StatusBar/Views/StatusBarView.xaml
src/Gemini/Themes/VS2013/BlueTheme.xaml
src/Gemini/Themes/VS2013/Controls/Button.xaml
src/Gemini/Themes/VS2013/Controls/CheckBox.xaml
src/Gemini/Themes/VS2013/Controls/ColorCanvas.xaml
src/Gemini/Themes/VS2013/Controls/ColorPicker.xaml
src/Gemini/Themes/VS2013/Controls/ComboBox.xaml
src/Gemini/Themes/VS2013/Controls/Converters/TreeViewIndentConverter.cs
src/Gemini/Themes/VS2013/Controls/Focus.xaml
src/Gemini/Themes/VS2013/Controls/Label.xaml
src/Gemini/Themes/VS2013/Controls/Merged.xaml
src/Gemini/Themes/VS2013/Controls/ScrollBar.xaml
src/Gemini/Themes/VS2013/Controls/Slider.xaml
src/Gemini/Themes/VS2013/Controls/TextBox.xaml
src/Gemini/Themes/VS2013/Controls/TreeView.xaml
src/Gemini/Themes/VS2013/DarkTheme.xaml
src/Gemini/Themes/VS2013/LightTheme.xaml

This commit generally improves the dark theme and also adds better control
styles to the Button, CheckBox, ColorPicker, ComboBox, ScrollBar, Slider,
TextBox and TreeView controls. In the theme implementation the resources
got moved from ApplicationResources to MainWindowResources so that the
settings window is not affected by the theme change.
Signed-off-by: Axel Gembe axel@gembe.net

Theme: Update a lot of control styles

---

src/Gemini.Modules.Inspector/Resources/Resources.xaml

The reset button only worked for objects that are not in a collapsible
group. When an object was in a group clicking the reset button resulted
in invoking the Reset method on the group instead of the object.
The solution seems to be to refresh the Action.TargetWithoutContext to
the current binding.

Fix reset button being attached to the group object in groups

---

.editorconfig
src/.editorconfig
src/Gemini.sln

VS2017 supports .editorconfig to set the code formatting values. This
patch sets resonable defaults based on what I observed the coding style
of the project to be.

Update .editorconfig, add coding style

---

src/Gemini/Framework/Document.cs
src/Gemini/Modules/UndoRedo/Design/DesignTimeHistoryViewModel.cs
src/Gemini/Modules/UndoRedo/IUndoRedoManager.cs
src/Gemini/Modules/UndoRedo/Services/UndoRedoManager.cs
src/Gemini/Modules/UndoRedo/ViewModels/HistoryItemViewModel.cs
src/Gemini/Modules/UndoRedo/ViewModels/HistoryViewModel.cs
src/Gemini/Modules/UndoRedo/Views/HistoryView.xaml.cs

I noticed while profiling my code that 99% of the CPU time to change the
undo redo stack is spent in Gemini instead of actually setting values.
This commit changes the undo / redo stack into a single stack with an
integer keeping track of what is undo and what is redo. This way we can
just easily synchronize the HistoryViewModel from the CollectionChanged
event of the UndoRedoManager stack. The advantage is that we can use an
item index in HistoryViewModel that is derived from the UndoRedoManager's
item index.
To do an undo / redo, we only need do undo / execute the needed actions
and update the UndoActions. The HistoryViewModel listens for UndoActions
changes and will update all the HistoryItemViewModel's ItemTypes. This has
the advantage of only refreshing the view once when all the …

Undo Redo: Improve performance when undo / redo stack changes

---

src/Gemini/Themes/VS2013/Controls/Menu.xaml

Based on the recommendation by @BHandle here https://github.com/tgjones/gemini/issues/291#issuecomment-443011486
Avoids WPF generating traces like:
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='System.Windows.Controls.ItemsControl', AncestorLevel='1''. BindingExpression:Path=HorizontalContentAlignment; DataItem=null; target element is 'MenuItemEx' (Name=''); target property is 'HorizontalContentAlignment' (type 'HorizontalAlignment')
System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='System.Windows.Controls.ItemsControl', AncestorLevel='1''. BindingExpression:Path=VerticalContentAlignment; DataItem=null; target element is 'MenuItemEx' (Name=''); …

Fix VS2013 MenuItem styles

---

src/Gemini.Demo/Modules/TextEditor/EditorProvider.cs
src/Gemini.Modules.CodeEditor/EditorProvider.cs
src/Gemini.sln
src/Gemini/Framework/Services/IEditorProvider.cs
src/Gemini/Framework/Tool.cs
src/Gemini/Modules/MainMenu/Models/CommandMenuItem.cs
src/Gemini/Modules/Shell/Commands/NewFileCommandHandler.cs
src/Gemini/Modules/Shell/Commands/OpenFileCommandHandler.cs
src/Gemini/Modules/Shell/ViewModels/ShellViewModel.cs
src/Gemini/Modules/Shell/Views/ShellView.xaml.cs

CommandMenuItem touch ups
-Add support for updating CommandMenuItem based on the underlying Command's values changing.
Fix #277 
-Fix OpenFileCommandHandler so it checks editorProviders.Length
Add CanCreateNew property to IEditorProvider
-This is based on #229  . This is useful when you only support reading/saving certain file types, but not creating them from scratch.
-Gemini supports net461, which is C# 7.3. If it only targeted dotnet versions that supported C# 8.0, CanCreateNew could have been implemented using a default interface member.
Add null guard in ShellView.UpdateFloatingWindows
-Add DataContext null check in UpdateFloatingWindows to avoid exceptions in the XAML designer.
Tool touch ups
-Change Tool CloseCommand to function the same as Document's, where it invokes …

General fix ups

---

src/.vscode/launch.json
src/Gemini.Demo/App.xaml
src/Gemini.Demo/DemoAppBootstrapper.cs
src/Gemini.Demo/Gemini.Demo.csproj
src/Gemini.Demo/Properties/PublishProfiles/FolderProfileNet5.pubxml
src/Gemini.Demo/Properties/PublishProfiles/FolderProfileNetCore31.pubxml
src/Gemini.Modules.CodeCompiler/Gemini.Modules.CodeCompiler.csproj
src/Gemini.Modules.CodeEditor/Gemini.Modules.CodeEditor.csproj
src/Gemini.Modules.ErrorList/Gemini.Modules.ErrorList.csproj
src/Gemini.Modules.GraphEditor/Gemini.Modules.GraphEditor.csproj
src/Gemini.Modules.Inspector/Gemini.Modules.Inspector.csproj
src/Gemini.Modules.Output/Gemini.Modules.Output.csproj
src/Gemini.Modules.PropertyGrid/Gemini.Modules.PropertyGrid.csproj
src/Gemini.sln
src/Gemini/AppBootstrapper.cs
src/Gemini/Framework/Results/OpenDocumentResult.cs
src/Gemini/Framework/Results/ShowToolResult.cs
src/Gemini/Framework/Results/ShowWindowResult.cs
src/Gemini/Gemini.csproj

Add net5.0-windows target.
Upgrade Caliburn.Micro from 4.0.104-alpha to 4.0.173 and make trivial changes in response to API changes around IDeactivate, which was changed to async. See https://github.com/Caliburn-Micro/Caliburn.Micro/commit/11d3d8207fd0e2aaf8f6956d791bb5f0ba2b037f.
Fix PublishSingleFile under .netcoreapp3.1. Files are extracted to a temp folder, so in addition to the CWD, AppContext.BaseDirectory must be enumerated by a DirectoryCatalog.
Fix PublishSingleFile under .net5.0-windows (and later, I imagine). Unlike .netcore, files are NOT extracted, unless you specify IncludeAllContentForSelfExtract=true in the .pubxml.
Add new DemoAppBootstrapper implementation to showcase how to support PublishSingleFile cases under .NET5. It is not used by default, requires user to change …

Update caliburn micro4.0.173 and fix PublishSingleFile

---

src/Gemini/Framework/Services/EditorFileType.cs
src/Gemini/Modules/Shell/Commands/NewFileCommandHandler.cs

Allow to provide an optional icon for editor file types, showing in "File > New" menu.

Support icon for editor file types

---

src/Gemini/Modules/Shell/Services/LayoutItemStatePersister.cs
src/Gemini/Modules/Shell/Views/LayoutUtility.cs

I encountered huge performance issue (if not a performance "blocker") at application start when I had at least one hidden tool in the restored layout. I was unable to do anything because of how busy the application was.
After some profiling, I found it was coming from the call to `ViewLocator.LocateForModel` in `CommandRouter.GetCommandHandlerForLayoutItem`. The problem is that when hidden tools are restored at loading, **they are set as `ActiveLayoutItem` despite not being shown and having no view attached to the view model**.
So when the `ViewLocator.LocateForModel` is called, it doesn't find a view from the view model provided by `ActiveLayoutItem` and instantiate a new view instance (without attaching it). And it does it every time commands are updated (on every click) and for every …

Fix tools loading at start, preventing performance issue on commands update

---

src/Gemini/Modules/MainMenu/Resources/Styles.xaml
src/Gemini/Themes/VS2013/Controls/Menu.xaml

Menu item icons were replaced by a check mark when checked. I added an alternative visual for menu items with icon.
Here is the difference with a checked "Open" command with icon and a checked "Open Graph" command without icon :

Add alternative checked visual for menu items with icons

---

src/Gemini/Modules/ToolBars/Models/CommandToolBarItem.cs

Tool bar item and menu item can both display the command text but only menu items handle underscore used as mnemonics shortcut marks.
This changes make the tool bar item display the same text as menu item when using `IconAndText` display mode.
Here is an example with `_O__p_en`, `S__a__v_e` and `Save All_` commands, edited to show edge cases :

Remove mnemonics shortcut marks for tool bar items.

---

src/Gemini/Framework/Commands/Command.cs
src/Gemini/Framework/Utils/ItemsControlUtility.cs
src/Gemini/Modules/MainMenu/Controls/MenuItemEx.cs
src/Gemini/Modules/ToolBars/Controls/ToolBarBase.cs
src/Gemini/Modules/ToolBars/Models/CommandToolBarItem.cs
src/Gemini/Modules/ToolBars/Resources/Styles.xaml

I added toolbar item binding on command visibility so it behave the same as menu item.
Because of that, I improved MenuItemEx and ToolBarBase so they call a new helper `ItemsControlUtility.UpdateSeparatorsVisibility` on added/removed items or item visibility changes. It prevent separators to appear at toolbar/menu start or end, or to have multiple successive separators since it might be possible with visibility changes.
I also updated `CommandTooBarItem` with changes on PropertyChanged handler, similar to `CommandMenuItem` ones done by commit f3de641.
Finally, command properties now use Set(). It will prevent PropertyChanged to be raised when values are not changing.

Handle toolbar command visibility, hide toolbar/menu separators when unnecessary

---

src/Gemini.Demo/Modules/FilterDesigner/ViewModels/ConnectionViewModel.cs
src/Gemini.Demo/Modules/FilterDesigner/ViewModels/GraphViewModel.cs
src/Gemini.Demo/Modules/FilterDesigner/Views/GraphView.xaml
src/Gemini.Demo/Modules/FilterDesigner/Views/GraphView.xaml.cs
src/Gemini.Modules.GraphEditor/Controls/ConnectionItem.cs
src/Gemini.Modules.GraphEditor/Controls/ConnectionItemsControl.cs
src/Gemini.Modules.GraphEditor/Controls/ElementItem.cs
src/Gemini.Modules.GraphEditor/Controls/GraphControl.cs
src/Gemini.Modules.GraphEditor/Themes/Generic.xaml

In some designers implementation the action of select a connection is a frequently requested requirement.
- ConnectionItemsControl : ListBox control added
- ConnectionItem : ListBoxItem control added
- Event ConnectionSelectionChanged in the GraphControl added
- SelectedConnections property in the GraphControl added
- Designer Gemini.Demo updated

make the connection items selectable in the Gemini.Modules.GraphEditor

---

src/Gemini/Modules/Settings/ViewModels/SettingsViewModel.cs

When you open the Tools->Options and change a setting then click Cancel the user would assume that opening the Options window again would show the original setting however it currently shows the unsaved settings that the user selected before clicking Cancel. Changing the PartCreationPolicy to NonShared fixes this issue.

SettingViewModel should be Non-Shared

---

src/Gemini/Framework/Document.cs
src/Gemini/Framework/LayoutItemBase.cs
src/Gemini/Framework/PersistedDocument.cs
src/Gemini/Modules/Shell/Converters/TruncateMiddleConverter.cs
src/Gemini/Modules/Shell/Views/ShellView.xaml
src/Gemini/Themes/VS2013/Controls/Tooltip.xaml

Documents which titles are longer than the Window width are annoying. This simple PO sets a length limit on the display name of the document in the way VS does, i,.e. "abcdef...xyz.ext".

Truncate-middle converter

---

src/Gemini/Modules/StatusBar/Views/StatusBarView.xaml.cs

fix for https://github.com/tgjones/gemini/pull/337#issuecomment-1038517917
View get null when Toolbox hasn't been never opened.

RefreshGridColumns() add null check

---

src/Directory.Build.props
src/Gemini.Demo/Gemini.Demo.csproj
src/Gemini.Modules.CodeCompiler/Gemini.Modules.CodeCompiler.csproj
src/Gemini.Modules.CodeEditor/Gemini.Modules.CodeEditor.csproj
src/Gemini.Modules.ErrorList/Gemini.Modules.ErrorList.csproj
src/Gemini.Modules.GraphEditor/Gemini.Modules.GraphEditor.csproj
src/Gemini.Modules.Inspector/Gemini.Modules.Inspector.csproj
src/Gemini.Modules.Output/Gemini.Modules.Output.csproj
src/Gemini.Modules.PropertyGrid/Gemini.Modules.PropertyGrid.csproj
src/Gemini/AppBootstrapper.cs
src/Gemini/Gemini.csproj

Move minimum .NET version from 461 to 462, required for Caliburn Micro 4.0.210.
Update Caliburn.Micro to 4.0.210.
Update MahApps.Metro to 2.4.9.
Update System.ComponentModel.Composition to 6.0.0.
Update Nerdbank.Gitversioning to 3.5.109.
Fix AppBootstrapper.OnStartup to use DisplayRootViewForAsync, as the synchronous API was removed last year.
Add System.Drawing.Common v6 reference to Inspector module to address issues with ScreenShotUtility using the Bitmap type. See: https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only.

Update to latest CM, net462, plus other nugets.

---

README.md
src/Gemini.Demo/Modules/FilterDesigner/MenuDefinitions.cs
src/Gemini.Demo/Modules/Home/Module.cs
src/Gemini.Modules.ErrorList/MenuDefinitions.cs
src/Gemini.Modules.Inspector/MenuDefinitions.cs
src/Gemini.Modules.Output/MenuDefinitions.cs
src/Gemini.Modules.PropertyGrid/MenuDefinitions.cs
src/Gemini/Framework/Menus/CommandMenuItemDefinition.cs
src/Gemini/Framework/Menus/ExcludeMenuDefinition.cs
src/Gemini/Framework/Menus/ExcludeMenuItemDefinition.cs
src/Gemini/Framework/Menus/ExcludeMenuItemGroupDefinition.cs
src/Gemini/Framework/Menus/MenuDefinition.cs
src/Gemini/Framework/Menus/MenuDefinitionBase.cs
src/Gemini/Framework/Menus/MenuItemDefinition.cs
src/Gemini/Framework/Menus/MenuItemGroupDefinition.cs
src/Gemini/Framework/Menus/TextMenuItemDefinition.cs
src/Gemini/Modules/MainMenu/MenuBuilder.cs
src/Gemini/Modules/MainMenu/MenuDefinitions.cs
src/Gemini/Modules/MainMenu/Models/MenuItemBase.cs
src/Gemini/Modules/Settings/MenuDefinitions.cs
src/Gemini/Modules/Shell/MenuDefinitions.cs
src/Gemini/Modules/Toolbox/MenuDefinitions.cs
src/Gemini/Modules/UndoRedo/MenuDefinitions.cs

In another project, I have a "DEBUG" menu which I only desire visibility of when there's a debugger attached. This exposes functionality which facilitates this within Gemini.
The existing Exclude MenuDefinition support is not enough, because there's no conditionality to them, and I did not want to limit my "DEBUG" menu support to only `#if DEBUG` (sometimes you have to debug Release! Or modules are not built with the same configs). The optional predicate now exposed on menu definitions is passed the `this` reference, so the predicate can use additional immediate context if other people find use out of this.
This is "dynamic" in that the predicate is evaluated at menu build time. This seemed like the Keep It Simple, Stupid way of going about this, rather than trying to get too fancy with …

Dynamic Menu item exclusion support

---

src/Gemini/Modules/Shell/Services/LayoutItemStatePersister.cs
src/Gemini/Modules/Shell/ViewModels/ShellViewModel.cs

Fix LayoutItemStatePersister.LoadState so that it has matching behavior with ShellViewModel.OnViewLoaded. This is due to aa7a8b5557a716f6e3027e46b904c53f80b2e46b (from a PR #318 that I originally made) adding support for calling a Tool's ActivateAsync on the first showing.
This was broken by 60ede6456f2048f77966d899945dc1cc433aa6bf in PR #328.

PR #328 ActivateAsync regression fix

---

src/Gemini/Framework/Services/IShell.cs
src/Gemini/Framework/Tool.cs
src/Gemini/Modules/Shell/Services/LayoutItemStatePersister.cs
src/Gemini/Modules/Shell/ViewModels/ShellViewModel.cs

I fixed an issue on tools restored as hidden at launch but never activated at layout loading or when shown.
It's a good idea to not activate hidden tools at layout loading but we need to activate them when they are first shown in that case. `IShell.ShowTool` will now activate tools if they are not active, even if the tools was already registered in the `IShell.Tools` collection at layout loading.
I also added a `IShell.RegisterTool` method and also cleaned the Tool class implementation, especially properties setters.

Ensure tools are activated when shown, clean Tool implementation

---

src/Gemini/AppBootstrapper.cs

The default import strategy of Gemini is to load all the assemblies next to executables and setup the composition with the contained imports.
It's a good approach but it can come with performance issues depending of the number and the nature of the assemblies.
In my case, it became a problem when I did a self-contained build for a specific runtime identifier. This add many assemblies next to the executable, including heavy ones, and my application startup became way slower.
That's why I suggest to move the code populating the AssemblySource into a virtual method so each Gemini applications can implement their own alternative approach to populate AssemblySource if they want. This allowed me to target or ignore assemblies depending on my own rules and the startup is now 10 times quicker.

Add new virtual method PopulateAssembly to customize assemblies import

---

src/Gemini/Framework/Document.cs
src/Gemini/Modules/UndoRedo/IUndoRedoManager.cs
src/Gemini/Modules/UndoRedo/Services/UndoRedoManager.cs
src/Gemini/Modules/UndoRedo/ViewModels/HistoryViewModel.cs
src/Gemini/Modules/UndoRedo/Views/HistoryView.xaml

I made some improvements on the undo redo system:
- Allow to override a new protected method `Document.CreateUndoRedoManager` to change the implementation of `IUndoRedoManager`.
- Add method `IUndoRedoManager.PushAction` to stack an action without executing it.
- Interesting when the first action implementation (the "do") is different from the redo, or executed before the action is stacked (for example, a painting brush draw a line continuously but push an action only when the brush is not applied anymore).
- Fix `UndoRedoManager.UndoAll` not calling `OnBegin` and `OnEnd`.
- Improve the History tool:
- Gray text for redo actions instead of undo actions. (more intuitive to see undone actions in gray)
- Selection synchronization fixed.
- Slider aligned on items.
- Text trimmed + tooltips …

Improve undo-redo

---

src/Gemini.Demo/Modules/Home/Commands/ViewHomeCommandHandler.cs
src/Gemini/Framework/Results/OpenDocumentResult.cs
src/Gemini/Framework/Results/ShowToolResult.cs
src/Gemini/Modules/Toolbox/Commands/ViewToolboxCommandHandler.cs

Both OpenDocumentResult and ShowToolResult imported IShell but their member variable was set to readonly, which resulted in a composition exception (member is not writable, see below). They are no longer readonly.
Additionally. no code was actually making use of the Show.Document/Tool helpers, which is likely how this went uncaught, despite the README.md providing an example of it for the HomeViewModel. ViewHome and ViewToolboxCommandHandler now use Show class instead of importing IShell themselves.
```
The composition produced a single composition error. The root cause is provided below. Review the CompositionException.Errors property for more detailed information.
1) Cannot set the value of 'Gemini.Framework.Results.OpenDocumentResult._shell' because the member is not writable. If the …
```

Fix cases of readonly on [Import]'s
