README.markdown

Caliburn.Micro has been moved to GitHub

Fixed Caliburn.Micro URL

---

src/Gemini.Modules.Inspector/InspectorBuilder.cs

Sometimes it is desirable to add single properties one by one, this can be done using this method.

Inspector: Add WithObjectProperty for single properties

---

src/Gemini.Modules.Inspector/Resources/Resources.xaml
src/Gemini.Modules.Output/Views/OutputView.xaml
src/Gemini/Modules/Toolbox/Views/ToolboxView.xaml
src/Gemini/Themes/Generic.xaml
src/Gemini/Themes/VS2013/BlueTheme.xaml
src/Gemini/Themes/VS2013/DarkTheme.xaml
src/Gemini/Themes/VS2013/LightTheme.xaml

Some updates for the dark theme, more to come

Dark theme update

---

src/Gemini.Modules.Inspector/Inspectors/EditorBase.cs

If the bound property descriptor does not support change events, try to
check if the owner is a type implementing INotifyPropertyChanged and
subscribe to the owners PropertyChanged events.

Inspector: Add support for INotifyPropertyChanged of PropertyOwner

---

.editorconfig

Add a .editorconfig file for consistent formatting

---

src/Gemini/Modules/UndoRedo/Views/HistoryView.xaml
src/Gemini/Themes/VS2013/BlueTheme.xaml
src/Gemini/Themes/VS2013/DarkTheme.xaml
src/Gemini/Themes/VS2013/LightTheme.xaml

UndoRedo: Make history view support the dark theme

---

src/Gemini/Themes/VS2013/Controls/Menu.xaml

Themes: Make context menu support the dark theme

---

src/Gemini.Modules.Inspector/Inspectors/EditorBase.cs
src/Gemini.Modules.Inspector/Inspectors/SelectiveUndoEditorBase.cs

Inspector: Only notify of property change if values are not equal

---

src/Gemini.Modules.Inspector/Inspectors/EditorBase.cs
src/Gemini.Modules.Inspector/Resources/Resources.xaml

Inspector: Add reset button to properties that can be reset

---

src/Rebracer.xml

Rebracer: Add space after casts

---

src/Gemini/Modules/UndoRedo/IUndoRedoManager.cs
src/Gemini/Modules/UndoRedo/Services/UndoRedoManager.cs

This will make it possible to handle changing the undo redo stack more
efficiently by batching writes and/or combining multiple value changes to
the same value.

Undo Redo: Add events to notify when a batch of actions starts and ends

---

src/Gemini.Modules.Inspector/Inspectors/EditorBase.cs
src/Gemini.Modules.Inspector/Inspectors/IEditor.cs
src/Gemini.Modules.Inspector/Properties/Resources.Designer.cs
src/Gemini.Modules.Inspector/Properties/Resources.de.resx
src/Gemini.Modules.Inspector/Properties/Resources.resx
src/Gemini.Modules.Inspector/Properties/Resources.zh-Hans.resx
src/Gemini.Modules.Inspector/Resources/Resources.xaml
src/Gemini.Modules.Inspector/ViewModels/InspectorViewModel.cs
src/Gemini.Modules.Inspector/Views/InspectorView.xaml

Inspector: Do not reset read only values

Inspector: Add reset all button to every inspector

---

src/Gemini.Modules.Inspector/Inspectors/EditorBase.cs

Inspector: Only add to undo redo if there is an active document

---

src/Gemini.Modules.Inspector/Inspectors/ColorEditorView.xaml
src/Gemini.Modules.Inspector/Inspectors/ColorEditorViewModel.cs

Color Picker: Add binding for UsingAlphaChannel

---

src/Gemini.Modules.Inspector/Inspectors/ColorEditorView.xaml
src/Gemini.Modules.Inspector/Properties/Resources.Designer.cs
src/Gemini.Modules.Inspector/Properties/Resources.de.resx
src/Gemini.Modules.Inspector/Properties/Resources.resx
src/Gemini.Modules.Inspector/Properties/Resources.zh-Hans.resx

Color Picker: Localization

---

README.markdown

README: Fix demo link

---

src/Gemini/Modules/MainMenu/Converters/CultureInfoNameConverter.cs

Settings: Fix null reference exception in culture info converter

---

src/Gemini.Demo/Gemini.Demo.csproj
src/Gemini.Demo/Properties/Resources.ru.resx
src/Gemini.Modules.CodeEditor/Gemini.Modules.CodeEditor.csproj
src/Gemini.Modules.CodeEditor/Properties/Resources.ru.resx
src/Gemini.Modules.ErrorList/Gemini.Modules.ErrorList.csproj
src/Gemini.Modules.ErrorList/Properties/Resources.ru.resx
src/Gemini.Modules.Inspector/Gemini.Modules.Inspector.csproj
src/Gemini.Modules.Inspector/Properties/Resources.ru.resx
src/Gemini.Modules.Output/Gemini.Modules.Output.csproj
src/Gemini.Modules.Output/Properties/Resources.ru.resx
src/Gemini.Modules.PropertyGrid/Gemini.Modules.PropertyGrid.csproj
src/Gemini.Modules.PropertyGrid/Properties/Resources.ru.resx
src/Gemini/Gemini.csproj
src/Gemini/Modules/MainMenu/ViewModels/MainMenuSettingsViewModel.cs
src/Gemini/Properties/Resources.ru.resx

This includes and needs #225 and #226 merged

Add Russian language

---

appveyor.yml
scripts/install-xna.ps1

Fix for errors per appveyor build.

---

src/Gemini/Modules/Toolbox/ViewModels/ToolboxViewModel.cs
src/Gemini/Modules/Toolbox/Views/ToolboxView.xaml

Added the possibility to search via name of ToolBoxItems

Added toolbox search functionality

---

src/Gemini/AppBootstrapper.cs

This commit has been separated from #290 for easy merge. Now we can use the latest Gu.Localization and Caliburn.Micro. Refer to #243.

 Using Resources.resx with InvariantCulture

---

.github/workflows/ci.yml

Use 5.0.x (x meaning the latest version in the 5.0 channel) for setup-dotnet
Hope this works!

Update ci.yml for .net5.0

---

src/Gemini/Modules/StatusBar/IStatusBar.cs
src/Gemini/Modules/StatusBar/IStatusBarView.cs
src/Gemini/Modules/StatusBar/ViewModels/StatusBarViewModel.cs
src/Gemini/Modules/StatusBar/Views/StatusBarView.xaml.cs

Reason : Default StatusBarView call RefreshGridColumns() once and there's no way to refresh columns again after this time. So I want to expose RefreshGridColumns() and user could refresh columns after they called AddItem() anytime.

Improve IStatusBar
